# environment.yml
name: lpad
channels:
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - python=3.8
  - primer3-py
  - biopython=1.78
  - pandas
  - blast
  - joblib
  - scipy
  - scikit-learn
